apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloaks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloaks
  template:
    metadata:
      labels:
        app: helloaks
    spec:
      containers:
        - name: helloaks
          image: vramakhelloaksreg.azurecr.io/helloaks
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80