name: BuildAndDeploy
"on":
    push:
        branches:
            - master
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: HelloAKS_RG
    AZURE_CONTAINER_REGISTRY: helloaksregistry
    CLUSTER_NAME: helloaks1
    CLUSTER_RESOURCE_GROUP: HelloAKS_RG
    CONTAINER_NAME: helloaks
    DEPLOYMENT_MANIFEST_PATH: |
        ./manifests/deployment.yml
        ./manifests/service.yml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ secrets.repository }}:${{ github.sha }} --registry ${{ secrets.registry }} -g ${{ secrets.resource_group }} -f ./HelloAKS/Dockerfile ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              name: Azure login
              with:
                creds: ${{ secrets.azure_credentials }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ secrets.cluster_name }}
                resource-group: ${{ secrets.resource_group }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: default
